### ISSUE TITLE
RadioCommunications deserializes appears to not work

### ISSUE THREAD

**Issue by znoble360** [crhowell3/open-dis-rust#10]
### What version of Open DIS Rust is running?

0.1.0-alpha.6

### What platform is your computer?

Linux 6.5.6-76060506-generic x86_64 x86_64

### What steps can reproduce the bug?

dat in this example is a `Vec<u8>`, and if I try to deserialize it, it just says Err(InvalidDISHeader), but when I deserialize without header, it deserializes as expected.
```rust
loop { 
    let dat = match conn.recv().await.unwrap();

    let mut bytes = BytesMut::from(dat.as_slice());
    let pdu_header = PduHeader::decode(&mut bytes);
    let body_data = BytesMut::from(&dat[12..]);

    match pdu_header.pdu_type {
        PduType::Transmitter => {
            // this does not work
            //let xmsn = TransmitterPdu::deserialize(bytes);

            // this *does* work
            let xmsn = TransmitterPdu::deserialize_without_header(body_data, pdu_header);
            println!("{:?}", xmsn);
            println!("{:?}", pdu_header.pdu_type);
            println!("{:?}", PduType::Transmitter);
            println!("{:?}", pdu_header);
        },
        _ => continue,
    }
}
```
So with 
```rust 
let xmsn = TransmitterPdu::deserialize(bytes);
```
the output is:
```
Err(InvalidDISHeader)
Transmitter
Transmitter
PduHeader { protocol_version: IEEE1278_1A_1998, exercise_id: 1, pdu_type: Transmitter, protocol_family: RadioCommunications, timestamp: 3066130581, length: 104, padding: 0 }
```

But with 
```rust 
let xmsn = TransmitterPdu::deserialize_without_header(body_data, pdu_header);
```
The output is:
```
Ok(TransmitterPdu { pdu_header: PduHeader { protocol_version: IEEE1278_1A_1998, exercise_id: 1, pdu_type: Transmitter, protocol_family: RadioCommunications, timestamp: 3459835265, length: 104, padding: 0 }, entity_id: EntityId { simulation_address: SimulationAddress { site_id: 50, application_id: 2 }, entity_id: 5 }, radio_id: 1, radio_entity_type: RadioEntityType { entity_kind: 7, domain: 0, country: 0, category: 0, nomenclature_version: 0, nomenclature: 0 }, transmit_state: 2, input_source: 0, padding1: 0, antenna_location: Vector3Double { x: 0.0, y: 0.0, z: 0.0 }, relative_antenna_location: Vector3Float { x: 0.0, y: 0.0, z: 0.0 }, antenna_pattern_type: 0, antenna_pattern_count: 0, frequency: 100, transmit_frequency_bandwidth: 25000.0, power: 40.0, modulation_type: ModulationType { spread_spectrum: 0, major: 0, detail: 0, system: 0 }, crypto_system: 0, crypto_key_id: 0, modulation_parameter_count: 0, padding2: 0, padding3: 0, modulation_parameter_list: [], antenna_pattern_list: [] })
Transmitter
Transmitter
PduHeader { protocol_version: IEEE1278_1A_1998, exercise_id: 1, pdu_type: Transmitter, protocol_family: RadioCommunications, timestamp: 3459835265, length: 104, padding: 0 }
```

### What is the expected behavior?

Transmission::deserialize should be able to take a BytesMut containing a pdu and pdu header, and deserialize it into a TranssmissionPdu

### What do you see instead?

Transmission::deserialize cannot take a BytesMut containing a pdu and pdu header, and deserialize it into a TranssmissionPdu

### Additional information

I have also seen this exact case with SignalPdu as well. I looked at the source code and it doesn't make sense why it would fail to detect the proper pdu_type, but for some reason that is the case. Am I doing something wrong here?

**Comment by crhowell3** [comment]
I have a hunch as to what this could be, but I'll have to test it myself. It is probably related to the lack of support currently for dynamically sized PDUs, as all of them are statically sized at this point in time. I will get back to this issue as soon as I can test it. Thanks for bringing attention to this.

**Comment by znoble360** [comment]
I've used the library a bit more since I opened this issue and noticed that when the signal pdu has a 16 bit encoded data packets the library panics

**Comment by crhowell3** [comment]
Finally got some time to reevaluate this issue. I've been looking through the TransmitterPdu code and referencing your use case above. I have not been able to replicate the issue unfortunately. I would expect my test suite to also fail for the `test radio_communications::transmitter_pdu::tests::deserialize_header` unit test, but it succeeds. All I'm doing in the `TransmitterPdu::deserialize()` method is checking the `pdu_type` field in the PduHeader and returning an error code if it is not a TransmitterPdu. In your example, your debug outputs clearly show that it is a TransmitterPdu header, so I am not sure what could be happening there. I'll continue to investigate, and hopefully I'll get to the bottom of it soon.

**Comment by crhowell3** [comment]
I am going to add `deserialize_without_header` tests to all the PDUs that I currently have implemented. Since I am unable to replicate the issue, and since no other responses have been given here, I am going to close it. If the issue arises again in the future and can be replicated, I'll reopen and address it.
